#!/bin/bash

# 1. 创建 random_fstrim.sh 脚本
echo -e "#!/bin/bash\n\nwhile true; do\n    sleep \$[RANDOM%60]m\n    sleep 360m\n    fstrim -av\ndone" | sudo tee /usr/local/bin/random_fstrim.sh > /dev/null
sudo chmod +x /usr/local/bin/random_fstrim.sh

# 2. 创建 random_fstrim.service
echo -e "[Unit]\nDescription=Random fstrim Service\n\n[Service]\nExecStart=/usr/local/bin/random_fstrim.sh\nRestart=always\n\n[Install]\nWantedBy=multi-user.target" | sudo tee /etc/systemd/system/random_fstrim.service > /dev/null

# 3. 使服务在系统启动时自动运行
sudo systemctl daemon-reload
sudo systemctl enable random_fstrim.service
sudo systemctl start random_fstrim.service
