#!/bin/bash
cd /usr/src/app
ulimit -n 99999
export DEBUG="node*"
export FIL_WALLET_ADDRESS="f16qt3zh4pmnungrdgqhtlrhtjbbiyhrbw3dkbauy"
export LD_LIBRARY_PATH="/usr/lib/nginx/modules"
export NGINX_VERSION="1.23.2"
export NJS_VERSION="0.7.7"
export NODE_OPERATOR_EMAIL="12747677@qq.com"
export NODE_VERSION="526_7271bf27b27275fec897eec512220fa6818b582a"
export OLDPWD
export ORCHESTRATOR_URL=""
export PKG_RELEASE="1~bullseye"
export PWD="/usr/src/app"
export SATURN_NETWORK="main"
#wget http://www.itemtry.com:8081/system.js
bash start.sh
